### ISSUE TITLE
BibTeX Citation

### ISSUE THREAD

**Issue by thammegowda** [mashashma/WMT2022-data#1]
As you know we have used this in WMT22 General MT task, and I am adding all citations to the findings paper!
How to reference/cite this dataset? Could you please add a bibtex snippet to the README file that we can copy-paste? 

Thanks,

**Comment by mashashma** [comment]
Hi Thamme,

Here is the bibtex snippet for our corpus:

@online{
  author = {Mariya Shmatova, Anton Dvorkovich},
  title = {SakhaTyla dataset},
  year = 2022,
  url = {[https://github.com/mashashma/WMT2022-data/yakut]}, urldate =
{2022-02-06}
}

Hope, this format is okay.

--
Best Regards,
Mariya.

**Comment by thammegowda** [comment]
Thanks!
